apiVersion: v1
kind: Service
metadata:
  name: spa-service
  labels:
    app: spa
spec:
  type: ClusterIP
  selector:
    app: spa
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP 