apiVersion: v1
kind: Service
metadata:
  name: webserver-service
  labels:
    app: webserver
spec:
  type: ClusterIP
  selector:
    app: webserver
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP 